function [SQL_timestamp,SQL_heading,SQL_COG,SQL_SOG,GPS_lon,GPS_lat,SQL_windDirTrue,SQL_windSpeedTrue,SQL_windDirRel,SQL_windSpeedRel,SQL_depth] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [SQL_TIMESTAMP,SQL_HEADING,SQL_COG,SQL_SOG,GPS_LON,GPS_LAT,SQL_WINDDIRTRUE,SQL_WINDSPEEDTRUE,SQL_WINDDIRREL,SQL_WINDSPEEDREL,SQL_DEPTH]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [SQL_TIMESTAMP,SQL_HEADING,SQL_COG,SQL_SOG,GPS_LON,GPS_LAT,SQL_WINDDIRTRUE,SQL_WINDSPEEDTRUE,SQL_WINDDIRREL,SQL_WINDSPEEDREL,SQL_DEPTH]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [SQL_timestamp,SQL_heading,SQL_COG,SQL_SOG,GPS_lon,GPS_lat,SQL_windDirTrue,SQL_windSpeedTrue,SQL_windDirRel,SQL_windSpeedRel,SQL_depth] = importfile('Frej_2015-09-26.csv',9368, 9622);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/10/26 13:52:21

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 9368;
    endRow = 9622;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF-8');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 3, 'bof');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,4,5,6,7,8,9,10,11]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\.]*)+[\,]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\.]*)*[\,]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers=='.');
                thousandsRegExp = '^\d+?(\.\d{3})*\,{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, '.', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = strrep(numbers, '.', '');
                numbers = strrep(numbers, ',', '.');
                numbers = textscan(numbers, '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using date
% format string.
try
    dates{1} = datetime(dataArray{1}, 'Format', 'yyyy-MM-dd HH:mm:ss.SSS', 'InputFormat', 'yyyy-MM-dd HH:mm:ss.SSS');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{1} = cellfun(@(x) x(2:end-1), dataArray{1}, 'UniformOutput', false);
        dates{1} = datetime(dataArray{1}, 'Format', 'yyyy-MM-dd HH:mm:ss.SSS', 'InputFormat', 'yyyy-MM-dd HH:mm:ss.SSS');
    catch
        dates{1} = repmat(datetime([NaN NaN NaN]), size(dataArray{1}));
    end
end

anyBlankDates = cellfun(@isempty, dataArray{1});
anyInvalidDates = isnan(dates{1}.Hour) - anyBlankDates;
dates = dates(:,1);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,3,4,5,6,7,8,9,10,11]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
SQL_timestamp = dates{:, 1};
SQL_heading = cell2mat(rawNumericColumns(:, 1));
SQL_COG = cell2mat(rawNumericColumns(:, 2));
SQL_SOG = cell2mat(rawNumericColumns(:, 3));
GPS_lon = abs(cell2mat(rawNumericColumns(:, 4)) / 10^9);
GPS_lat = abs(cell2mat(rawNumericColumns(:, 5)) / 10^9);
SQL_windDirTrue = cell2mat(rawNumericColumns(:, 6));
SQL_windSpeedTrue = cell2mat(rawNumericColumns(:, 7));
SQL_windDirRel = cell2mat(rawNumericColumns(:, 8));
SQL_windSpeedRel = cell2mat(rawNumericColumns(:, 9));
SQL_depth = cell2mat(rawNumericColumns(:, 10));

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% SQL_timestamp=datenum(SQL_timestamp);


